/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FetchData {
        "artist": any;
    }
    interface ParallelGraph {
        "data": string;
        "height": number;
        "width": number;
    }
}
declare global {
    interface HTMLFetchDataElement extends Components.FetchData, HTMLStencilElement {
    }
    var HTMLFetchDataElement: {
        prototype: HTMLFetchDataElement;
        new (): HTMLFetchDataElement;
    };
    interface HTMLParallelGraphElement extends Components.ParallelGraph, HTMLStencilElement {
    }
    var HTMLParallelGraphElement: {
        prototype: HTMLParallelGraphElement;
        new (): HTMLParallelGraphElement;
    };
    interface HTMLElementTagNameMap {
        "fetch-data": HTMLFetchDataElement;
        "parallel-graph": HTMLParallelGraphElement;
    }
}
declare namespace LocalJSX {
    interface FetchData {
        "artist"?: any;
    }
    interface ParallelGraph {
        "data"?: string;
        "height"?: number;
        "width"?: number;
    }
    interface IntrinsicElements {
        "fetch-data": FetchData;
        "parallel-graph": ParallelGraph;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fetch-data": LocalJSX.FetchData & JSXBase.HTMLAttributes<HTMLFetchDataElement>;
            "parallel-graph": LocalJSX.ParallelGraph & JSXBase.HTMLAttributes<HTMLParallelGraphElement>;
        }
    }
}
